global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'jetson-cadvisor'
    static_configs:
      - targets: ['localhost:8080']
        labels:
          instance_name: 'jetson-cadvisor'
  - job_name: 'jetson-stat'
    static_configs:
      - targets: ['localhost:3030']
        labels:
          instance_name: 'jetson-stat'
